[package]
name = "threematrix"
version = "0.1.0"
edition = "2021"

[dependencies]
threema-gateway = "0.15.1"
tokio = { version = "1", features = ["full"] }
actix-web = "4"
rand = "0.8.5"
toml = "0.5.9"
serde = "1.0.137"
serde_derive = "^1.0"
